### ISSUE TITLE
Travis CI Build Instructions (Just in case others are looking for it)

### ISSUE THREAD

**Issue by Montana** [AstraZeneca/kallisto#34]
Currently using Kallisto, and I used Travis, but I thought I'd share my `yml` just in case anyone else ran into this issue as well! 

I think it's imperative to have instructions for all CI/CD's, so I wrote some Travis build instructions for this repo for AstraZeneca, just incase, and this happened to be what I used when implementing CI/CD of my liking/choice. 

```yaml

--- 
language: python
matrix: 
  include: 
    - 
      dist: xenial
      os: linux
      python: 3.6
      sudo: required
    - 
      dist: xenial
      os: linux
      python: 3.7
      sudo: required
    - 
      env: PYTHON=36
      language: generic
      os: osx
      osx_image: xcode10
script: 
  - "pip install nox"
  - "pip install poetry"

# Travis CI Build Instructions for Kallisto made by Montana Mendy
# Just incase if needed by AstraZeneca
```
-Montana Mendy
